import { z } from "zod";

/**
 * Bounded diagnosis taxonomy the AI Diagnosis Agent may choose from. This is
 * deliberately distinct from `@recoverai/core`'s `FailureReasonCode` — that
 * enum is a technical classification produced by the deterministic failure
 * classifier; this one is the AI-facing, merchant-relevant categorization the
 * model (or the deterministic fallback) is allowed to conclude. Neither an
 * LLM response nor the deterministic engine can produce a value outside this
 * list — Zod rejects anything else at the boundary.
 */
export const DIAGNOSIS_CATEGORIES = [
  "issuer_decline",
  "insufficient_funds",
  "upi_failure",
  "network_timeout",
  "expired_card",
  "repeated_failure",
  "checkout_abandonment",
  "refund_related",
  "non_retryable",
  "insufficient_evidence",
  "unknown",
] as const;
export type DiagnosisCategory = (typeof DIAGNOSIS_CATEGORIES)[number];
export const diagnosisCategorySchema = z.enum(DIAGNOSIS_CATEGORIES);

/** Bounded recoverability verdict — never a free-form string. */
export const RECOVERABILITY_ASSESSMENTS = [
  "LIKELY_RECOVERABLE",
  "POSSIBLY_RECOVERABLE",
  "LOW_RECOVERABILITY",
  "INSUFFICIENT_EVIDENCE",
] as const;
export type RecoverabilityAssessment = (typeof RECOVERABILITY_ASSESSMENTS)[number];
export const recoverabilityAssessmentSchema = z.enum(RECOVERABILITY_ASSESSMENTS);

/**
 * Bounded set of intervention categories. This is a decision-support agent,
 * not an execution agent — these values describe what *could* be done, they
 * never trigger anything themselves. Arbitrary action types cannot appear
 * here; anything outside this list fails schema validation.
 */
export const INTERVENTION_TYPES = [
  "RETRY",
  "ALTERNATE_PAYMENT_METHOD",
  "RECOVERY_LINK",
  "CUSTOMER_NOTIFICATION",
  "WAIT_AND_RETRY",
  "HUMAN_REVIEW",
  "NO_ACTION",
] as const;
export type InterventionType = (typeof INTERVENTION_TYPES)[number];
export const interventionTypeSchema = z.enum(INTERVENTION_TYPES);

export const EVIDENCE_TYPES = [
  "transaction",
  "payment_attempt",
  "customer_history",
  "risk_signal",
  "derived_signal",
] as const;
export type EvidenceType = (typeof EVIDENCE_TYPES)[number];
export const evidenceTypeSchema = z.enum(EVIDENCE_TYPES);

/**
 * A single, independently-checkable fact the diagnosis is grounded in.
 * Every `EvidenceItem` is generated by the deterministic layer — never by
 * the model — and given a fixed `id`. An LLM response can only *cite* ids
 * from the bundle it was given; it cannot invent new evidence content (see
 * `validation.ts`).
 */
export const evidenceItemSchema = z.object({
  id: z.string().min(1),
  type: evidenceTypeSchema,
  source: z.string().min(1),
  fact: z.string().min(1),
  relevance: z.string().min(1),
  weight: z.number().min(0).max(1),
});
export type EvidenceItem = z.infer<typeof evidenceItemSchema>;

export const retryRecommendationSchema = z.object({
  recommended: z.boolean(),
  /** 0 when a retry is not recommended at all. */
  maxAttempts: z.number().int().min(0).max(5),
  reasoning: z.string().min(1),
});
export type RetryRecommendation = z.infer<typeof retryRecommendationSchema>;

export const diagnosisMetadataSchema = z.object({
  mode: z.enum(["deterministic", "llm"]),
  provider: z.string().nullable(),
  model: z.string().nullable(),
  agentVersion: z.string().min(1),
  generatedAt: z.string().min(1),
  fallbackUsed: z.boolean(),
  fallbackReason: z.string().optional(),
});
export type DiagnosisMetadata = z.infer<typeof diagnosisMetadataSchema>;

/**
 * The final, structured diagnosis — the only artifact either code path
 * (deterministic or LLM-assisted) is allowed to hand back to a caller.
 * `evidence` always contains full `EvidenceItem` objects sourced from the
 * deterministic evidence bundle, never model-authored content.
 */
export const diagnosisSchema = z.object({
  transactionId: z.string().min(1),
  category: diagnosisCategorySchema,
  confidence: z.number().min(0).max(1),
  evidence: z.array(evidenceItemSchema).min(1),
  recoverabilityAssessment: recoverabilityAssessmentSchema,
  retryRecommendation: retryRecommendationSchema,
  interventionEligibility: z.array(interventionTypeSchema).min(1),
  explanation: z.string().min(1),
  limitations: z.array(z.string()),
  metadata: diagnosisMetadataSchema,
});
export type Diagnosis = z.infer<typeof diagnosisSchema>;

/**
 * The narrower schema actually requested FROM the model. It references
 * evidence by `id` only (`evidenceIds`) rather than re-emitting evidence
 * content — the model selects which known facts support its conclusion, but
 * cannot author the facts themselves. `GroundedDiagnosisAgent` resolves
 * `evidenceIds` back to full `EvidenceItem`s from the deterministic bundle
 * before returning a `Diagnosis`.
 */
export const llmDiagnosisResponseSchema = z.object({
  transactionId: z.string().min(1),
  category: diagnosisCategorySchema,
  confidence: z.number().min(0).max(1),
  evidenceIds: z.array(z.string().min(1)).min(1),
  recoverabilityAssessment: recoverabilityAssessmentSchema,
  retryRecommendation: retryRecommendationSchema,
  interventionEligibility: z.array(interventionTypeSchema).min(1),
  explanation: z.string().min(1),
  limitations: z.array(z.string()),
});
export type LlmDiagnosisResponse = z.infer<typeof llmDiagnosisResponseSchema>;
